from __future__ import annotations

from io import BytesIO
from typing import Optional

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

from app.models.shipment import Shipment, Party, Item


def _fmt_party(p: Optional[Party]) -> list[str]:
    if not p:
        return ["(missing)"]
    lines = []
    if p.Name:
        lines.append(p.Name)
    if p.AddressLine1:
        # AddressLine1 sometimes contains \n (like ATTN lines). Split safely.
        lines.extend([ln.strip() for ln in str(p.AddressLine1).splitlines() if ln.strip()])
    if p.AddressLine2:
        lines.append(p.AddressLine2)
    city_state_zip = " ".join([x for x in [p.City, p.StateProvince, p.PostalCode] if x])
    if city_state_zip.strip():
        lines.append(city_state_zip)
    if p.CountryCode:
        lines.append(p.CountryCode)
    if p.Contact and p.Contact.Phone:
        lines.append(f"Phone: {p.Contact.Phone}")
    return lines or ["(missing)"]


def _fmt_item_row(i: Item) -> str:
    desc = i.Description or ""
    nmfc = i.NmfcCode or ""
    fc = ""
    if i.FreightClasses and i.FreightClasses.FreightClass is not None:
        fc = str(i.FreightClasses.FreightClass)

    qty = ""
    if i.Quantities and i.Quantities.Actual is not None:
        qty = f"{i.Quantities.Actual:g} {i.Quantities.Uom or ''}".strip()

    wt = ""
    if i.Weights and i.Weights.Actual is not None:
        wt = f"{i.Weights.Actual:g} {i.Weights.Uom or ''}".strip()

    dims = ""
    if i.Dimensions and all(v is not None for v in [i.Dimensions.Length, i.Dimensions.Width, i.Dimensions.Height]):
        dims = f'{i.Dimensions.Length:g}x{i.Dimensions.Width:g}x{i.Dimensions.Height:g} {i.Dimensions.Uom or ""}'.strip()

    parts = [p for p in [desc, f"FC {fc}" if fc else "", f"NMFC {nmfc}" if nmfc else "", qty, wt, dims] if p]
    return " | ".join(parts)


def render_shipment_confirmation_pdf(s: Shipment) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=LETTER)
    width, height = LETTER

    left = 0.75 * inch
    top = height - 0.75 * inch
    line_h = 14

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(left, top, "Shipment Confirmation")

    c.setFont("Helvetica", 10)
    y = top - 22

    primary = s.primary_reference() or "—"
    status = s.Status or "—"
    c.drawString(left, y, f"Primary Ref: {primary}")
    c.drawString(left + 3.5 * inch, y, f"Status: {status}")
    y -= 16

    # Dates
    if s.Dates:
        c.drawString(left, y, f"Earliest Pickup: {s.Dates.EarliestPickupDate or '—'}")
        c.drawString(left + 3.5 * inch, y, f"Latest Pickup: {s.Dates.LatestPickupDate or '—'}")
        y -= 14
        c.drawString(left, y, f"Earliest Drop: {s.Dates.EarliestDropDate or '—'}")
        c.drawString(left + 3.5 * inch, y, f"Latest Drop: {s.Dates.LatestDropDate or '—'}")
        y -= 18

    # Service codes
    svc = s.selected_service_codes()
    c.drawString(left, y, f"Service Codes: {', '.join(svc) if svc else '—'}")
    y -= 22

    # Shipper / Consignee blocks
    c.setFont("Helvetica-Bold", 11)
    c.drawString(left, y, "Shipper")
    c.drawString(left + 3.5 * inch, y, "Consignee")
    y -= 14

    c.setFont("Helvetica", 10)
    ship_lines = _fmt_party(s.Shipper)
    cons_lines = _fmt_party(s.Consignee)

    max_lines = max(len(ship_lines), len(cons_lines))
    for idx in range(max_lines):
        if idx < len(ship_lines):
            c.drawString(left, y, ship_lines[idx][:60])
        if idx < len(cons_lines):
            c.drawString(left + 3.5 * inch, y, cons_lines[idx][:60])
        y -= 12

    y -= 14

    # Items
    c.setFont("Helvetica-Bold", 11)
    c.drawString(left, y, f"Items ({len(s.Items)})")
    y -= 14

    c.setFont("Helvetica", 9)
    for item in s.Items:
        row = _fmt_item_row(item)
        # basic wrapping
        wrap_width = 105
        chunks = [row[i:i + wrap_width] for i in range(0, len(row), wrap_width)] or [""]
        for ch in chunks:
            if y < 0.75 * inch:
                c.showPage()
                c.setFont("Helvetica", 9)
                y = height - 0.75 * inch
            c.drawString(left, y, ch)
            y -= 11
        y -= 3

    # Footer
    if y < 1.0 * inch:
        c.showPage()
        y = height - 0.75 * inch

    c.setFont("Helvetica-Oblique", 8)
    c.drawString(left, 0.6 * inch, "Generated by ULP_PDF_PIPELINE")

    c.showPage()
    c.save()
    return buf.getvalue()
